font_family      CaskaydiaCove Nerd Font
bold_font        CaskaydiaCove Nerd Font Bold
italic_font      CaskaydiaCove Nerd Font Italic
bold_italic_font CaskaydiaCove Nerd Font Bold Italic

font_size 15

# cursor
cursor_blink_interval 0
cursor_shape block

# mouse
mouse_hide_wait 10.0

# keybindings
map f11 toggle_fullscreen

# theme
include theme.conf

# tabs
include tabs.conf
